const CONFIG={apiUrl:'https://script.google.com/macros/s/AKfycbz8Z_CrpY62Rrg6j7_httvAEDUDc0uwc4ZR6wDCBgedIHJFLg9PxVPycti3W_mJTDSv/exec',token:'17HVhQjZkfEblaWz3dwmALoHIBq9aiX8kfuSq5Ut_JPE',usuario:'Administrativo'};
const $=s=>document.querySelector(s), money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0), date=v=>v?new Date(v).toLocaleDateString('pt-BR',{timeZone:'UTC'}):'';
function toast(m,err=false){let e=$('.toast')||Object.assign(document.createElement('div'),{className:'toast'});e.textContent=m;e.className='toast show'+(err?' error':'');document.body.append(e);setTimeout(()=>e.classList.remove('show'),3000)}
async function api(action,data={},method='GET'){const spin=$('.spinner');if(spin)spin.style.display='inline-block';try{let u=CONFIG.apiUrl+'?'+new URLSearchParams({action,token:CONFIG.token,...(method==='GET'?data:{})});let r=await fetch(u,{method,headers:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify({action,token:CONFIG.token,usuario:CONFIG.usuario,...data}):undefined});let j=await r.json();if(!j.ok)throw Error(j.error);return j.data}catch(e){toast(e.message,true);throw e}finally{if(spin)spin.style.display='none'}}
function page(){return location.pathname.split('/').pop()||'index.html'}function nav(){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===page()))}
function csv(rows,name){const s=rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download=name;a.click()}
document.addEventListener('DOMContentLoaded',async()=>{nav();const p=page();if(p==='index.html')dashboard();if(p==='clientes.html')clientes();if(p==='emitir.html')emitir();if(p==='boletos.html')boletos();if(p==='imprimir.html')imprimir()});
async function dashboard(){let d=await api('dashboard');$('#cards').innerHTML=[['Emitidos',d.total],['Pendentes',d.pendentes],['Pagos',d.pagos],['Em aberto',money(d.aberto)],['Recebido',money(d.recebido)]].map((x,i)=>`<div class="card ${i===4?'green':''}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');let vals=Object.values(d.mensal),max=Math.max(...vals,1);$('#chart').innerHTML=Object.entries(d.mensal).map(([m,v])=>`<div class="bar" style="height:${v/max*175}px" title="${v} emissão(ões)"><small>${m.slice(5)}</small></div>`).join('')||'<p class="sub">Ainda não há emissões.</p>'}
async function clientes(){let rows=[];const load=async()=>{rows=await api('listClientes',{q:$('#search').value});$('#rows').innerHTML=rows.map(x=>`<tr><td>${x.Nome}</td><td>${x.CPF_CNPJ}</td><td>${x.Telefone||''}</td><td>${x.Email||''}</td><td><button class="secondary" onclick='editClient(${JSON.stringify(x)})'>Editar</button> <button class="danger" onclick="delClient('${x.ID}')">Excluir</button></td></tr>`).join('')};window.editClient=x=>{Object.entries({id:x.ID,nome:x.Nome,cpfCnpj:x.CPF_CNPJ,telefone:x.Telefone,email:x.Email,endereco:x.Endereco,cidade:x.Cidade,estado:x.Estado,cep:x.CEP}).forEach(([k,v])=>$('#clientForm [name='+k+']').value=v||'');scrollTo(0,0)};window.delClient=async id=>{if(confirm('Excluir este cliente?')){await api('deleteCliente',{id},'POST');load()}};$('#search').oninput=load;$('#export').onclick=()=>csv([['Nome','CPF/CNPJ','Telefone','E-mail'],...rows.map(x=>[x.Nome,x.CPF_CNPJ,x.Telefone,x.Email])],'clientes.csv');$('#clientForm').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));await api(d.id?'updateCliente':'createCliente',d,'POST');toast('Cliente salvo.');e.target.reset();load()};load()}
async function emitir(){const cs=await api('listClientes');$('#idCliente').innerHTML='<option value="">Selecione</option>'+cs.map(x=>`<option value="${x.ID}">${x.Nome} — ${x.CPF_CNPJ}</option>`).join('');$('#boletoForm').onsubmit=async e=>{e.preventDefault();let d=await api('createBoleto',Object.fromEntries(new FormData(e.target)),'POST');toast('Boleto emitido.');location.href='imprimir.html?id='+encodeURIComponent(d.ID_Boleto)}}
async function boletos(){let rows=[],pg=1;const load=async()=>{let f=Object.fromEntries(new FormData($('#filters')));rows=await api('listBoletos',f);pg=1;render()};const render=()=>{let part=rows.slice((pg-1)*10,pg*10);$('#rows').innerHTML=part.map(x=>`<tr><td>${x.ID_Boleto}</td><td>${x.NomeCliente}</td><td>${money(x.Valor)}</td><td>${date(x.Vencimento)}</td><td><span class="badge ${x.Status}">${x.Status}</span></td><td><select onchange="status('${x.ID_Boleto}',this.value)">${['Pendente','Pago','Cancelado','Vencido'].map(s=>`<option ${s===x.Status?'selected':''}>${s}</option>`).join('')}</select> <a class="button" href="imprimir.html?id=${x.ID_Boleto}">Imprimir</a></td></tr>`).join('');$('#pager').textContent=`Página ${pg} de ${Math.max(1,Math.ceil(rows.length/10))}`};window.status=async(id,status)=>{await api('updateStatus',{id,status},'POST');toast('Status atualizado.');load()};$('#filters').oninput=load;$('#prev').onclick=()=>{if(pg>1){pg--;render()}};$('#next').onclick=()=>{if(pg*10<rows.length){pg++;render()}};$('#export').onclick=()=>csv([['Número','Cliente','Valor','Vencimento','Status'],...rows.map(x=>[x.ID_Boleto,x.NomeCliente,x.Valor,date(x.Vencimento),x.Status])],'boletos.csv');load()}
async function imprimir(){let id=new URLSearchParams(location.search).get('id'),b=(await api('listBoletos',{q:id})).find(x=>x.ID_Boleto===id),c=(await api('listClientes')).find(x=>x.ID===b.ID_Cliente);$('#print').innerHTML=`<h1>EMPRESA — Boleto interno</h1><hr><p><b>Cliente:</b> ${c.Nome}<br>${c.Endereco||''} ${c.Cidade||''} ${c.Estado||''}<br>CPF/CNPJ: ${c.CPF_CNPJ}</p><h2>${money(b.Valor)}</h2><p><b>Vencimento:</b> ${date(b.Vencimento)} &nbsp; <b>Nosso número:</b> ${b.NossoNumero}</p><div class="panel"><b>Linha digitável</b><h2>${b.LinhaDigitavel}</h2></div><p>Documento de controle interno — não é boleto bancário.</p>`;$('#printBtn').onclick=()=>window.print()}
